In [2]:
import pandas as pd

In [3]:
import json

In [4]:
with open("ECBplus-prep/subtopic_names.json") as json_file:
    ecbplus_subtopics_list = json.load(json_file)

with open("ECBplus-prep/train_val_test_split.json") as json_file:
    train_val_test_split_dict = json.load(json_file)

In [5]:
#ecbplus_subtopics_list

In [6]:
topic_number_list = []
for k,v in ecbplus_subtopics_list.items():
    splitted = k.split("ecb")
    topic_number = int(splitted[0])
    topic_number_list.append(topic_number)
    
topic_number_list = set(topic_number_list)
full_number_list = set(range(1,46))
full_number_list.difference(topic_number_list)
#Check if topics 15 and 17 are invalid
# According to (Cybulska and Vossen 2014), there are indeed 43 topics

{15, 17}

In [7]:
#train_val_test_split_dict["train"]

In [8]:
# Explore output_data folder from ECB+

In [9]:
#All ECB= mentions
ecbplus_mentions = pd.read_csv("ECBplus-prep/output_data/all_mentions.csv")
ecbplus_conll = pd.read_csv('ECBplus-prep/output_data/conll.csv')
#Connll is at token level and references each key up to document level and cluster reference

In [10]:
len(ecbplus_conll)

377367

In [11]:
len(ecbplus_mentions)

15094

In [12]:
ecbplus_conll.head()

,Unnamed: 0,topic/subtopic_name/doc,sent_id,token_id,token,reference
0,0,1/1ecb/10,0,0,Perennial,-
1,1,1/1ecb/10,0,1,party,-
2,2,1/1ecb/10,0,2,girl,-
3,3,1/1ecb/10,0,3,Tara,(HUM16236184328979740
4,4,1/1ecb/10,0,4,Reid,HUM16236184328979740)

In [13]:
with open("ECBplus-prep/output_data/entities_mentions.json") as json_file:
    ecb_entities_mentions = json.load(json_file)

with open("ECBplus-prep/output_data/event_mentions.json") as json_file:
    ecb_events_mentions = json.load(json_file)

### NewsWCL50

In [14]:
newswcl50_mentions = pd.read_csv("NewsWCL50-prep/output_data/all_mentions.csv")
newswcl50_conll = pd.read_csv('NewsWCL50-prep/output_data/conll.csv')

In [15]:
newswcl50_mentions.mention_type.unique()

array(['COUNTRY', 'ACTOR', 'OBJECT', 'GROUP', 'EVENT', 'ACTION'],
      dtype=object)

In [16]:
newswcl50_mentions.shape

(4524, 27)

In [17]:
newswcl50_conll.head()

   Unnamed: 0 topic/subtopic_name/doc  sent_id  token_id  token reference
0           0                 0/0/0_L        0         0   WEST         -
1           1                 0/0/0_L        0         1   PALM         -
2           2                 0/0/0_L        0         2  BEACH         -
3           3                 0/0/0_L        0         3      ,         -
4           4                 0/0/0_L        0         4   Fla.         -

In [18]:
with open("NewsWCL50-prep/output_data/entities_mentions.json") as json_file:
    newswcl50_entities_mentions = json.load(json_file)

with open("NewsWCL50-prep/output_data/event_mentions.json") as json_file:
    newswcl50_events_mentions = json.load(json_file)

In [19]:
len(newswcl50_entities_mentions)

3894

In [20]:
len(newswcl50_events_mentions)

630

#### More entities than events

## MEANTIME

In [21]:
meantime_mentions = pd.read_csv("MEANTIME-prep/output_data/all_mentions.csv").query("language=='english'")
meantime_conll = pd.read_csv('MEANTIME-prep/output_data/conll.csv')
#Still need to filter conll to get only the english mentions

In [22]:
with open("MEANTIME-prep/output_data/entities_mentions.json") as json_file:
    meantime_entities_mentions = json.load(json_file)
    meantime_entities_mentions = [x for x in meantime_entities_mentions if x["language"]=="english"]
with open("MEANTIME-prep/output_data/event_mentions.json") as json_file:
    meantime_events_mentions = json.load(json_file)
    meantime_events_mentions = [x for x in meantime_events_mentions if x["language"]=="english"]

In [23]:
len(meantime_entities_mentions)

3762

In [24]:
len(meantime_events_mentions)

2672

## Summary

In [25]:
len(ecbplus_mentions.coref_chain.unique())

4886

In [26]:
len(ecb_events_mentions)

5000

In [27]:
len(ecb_entities_mentions)

10094

In [28]:
# Print table header
# Define column widths
col_width = 18
format_string= "{:<{}}{:<{}}{:<{}}{:<{}}{:<{}}"
print(format_string.format("Dataset", col_width, "Tokens", col_width, "Coreference Chains", col_width,"Entity mentions", col_width, "Event mentions", col_width))

# Print table rows
print(format_string.format("ECB+", col_width, len(ecbplus_conll), col_width, len(ecbplus_mentions), col_width, len(ecb_entities_mentions), col_width, len(ecb_events_mentions), col_width))
print(format_string.format("newswcl50", col_width, len(newswcl50_conll), col_width, len(newswcl50_mentions), col_width, len(newswcl50_entities_mentions), col_width, len(newswcl50_events_mentions), col_width))
print(format_string.format("meantime", col_width, len(meantime_conll), col_width, len(meantime_mentions), col_width, len(newswcl50_entities_mentions), col_width, len(meantime_events_mentions), col_width))

Dataset           Tokens            Coreference ChainsEntity mentions   Event mentions
ECB+              377367            15094             10094             5000
newswcl50         49591             4524              3894              630
meantime          169227            6434              3894              2672

In [29]:
meantime_mentions.columns

Index(['Unnamed: 0', 'coref_chain', 'mention_ner', 'mention_head_pos',
       'mention_head_lemma', 'mention_head', 'mention_head_id', 'doc_id',
       'doc_id_full', 'is_continuous', 'is_singleton', 'mention_id',
       'mention_type', 'mention_full_type', 'score', 'sent_id',
       'mention_context', 'tokens_number', 'tokens_str', 'tokens_text',
       'topic_id', 'topic', 'subtopic', 'coref_type', 'description',
       'language', 'conll_doc_key'],
      dtype='object')

In [30]:
ecbplus_mentions.head(1)

,Unnamed: 0,coref_chain,mention_ner,mention_head_pos,mention_head_lemma,mention_head,mention_head_id,doc_id,doc,is_continuous,...,tokens_number,tokens_str,tokens_text,topic_id,topic,subtopic_id,subtopic,coref_type,description,conll_doc_key
0,1_10ecb_TIM16236441119149059_3_11_TpBs,TIM16236441119149059,O,ADP,on,on,11,10,1_10ecb,True,...,"[11, 12]",on Tuesday,"['on', 'Tuesday']",1,1,1ecb,T. Reid checks into rehab in 2008,IDENTITY,t1b_friday,1/1ecb/10

In [32]:
import os
def read_files(config, split_name):
    docs_path = os.path.join(config.data_folder, split_name + '.json')
    mentions_path = os.path.join(config.data_folder,
                                    split_name + '_{}.json'.format(config.mention_type))
    with open(docs_path, 'r') as f:
        documents = json.load(f)

    mentions = []
    if config.use_gold_mentions:
        with open(mentions_path, 'r') as f:
            self.mentions = json.load(f)

In [34]:
class Config():
    def __init__(self, data_folder,use_gold_mentions):
        self.data_folder = data_folder

In [36]:
config = Config(data_folder="ECBplus-prep/output_data/")

In [ ]:
read_files('test')