In [1]:
import pandas as pd
import torch

In [2]:
import json

In [3]:
with open("ECBplus-prep/subtopic_names.json") as json_file:
    ecbplus_subtopics_list = json.load(json_file)

with open("ECBplus-prep/train_val_test_split.json") as json_file:
    train_val_test_split_dict = json.load(json_file)

In [4]:
#ecbplus_subtopics_list

In [5]:
topic_number_list = []
for k,v in ecbplus_subtopics_list.items():
    splitted = k.split("ecb")
    topic_number = int(splitted[0])
    topic_number_list.append(topic_number)
    
topic_number_list = set(topic_number_list)
full_number_list = set(range(1,46))
full_number_list.difference(topic_number_list)
#Check if topics 15 and 17 are invalid
# According to (Cybulska and Vossen 2014), there are indeed 43 topics

{15, 17}

In [6]:
#train_val_test_split_dict["train"]

In [7]:
# Explore output_data folder from ECB+

In [8]:
#All ECB= mentions
ecbplus_mentions = pd.read_csv("ECBplus-prep/output_data/all_mentions.csv")
ecbplus_conll = pd.read_csv('ECBplus-prep/output_data/conll.csv')
#Connll is at token level and references each key up to document level and cluster reference

In [9]:
len(ecbplus_conll)

377367

In [10]:
len(ecbplus_mentions)

15094

In [11]:
ecbplus_conll.head()

,Unnamed: 0,topic/subtopic_name/doc,sent_id,token_id,token,reference
0,0,1/1ecb/10,0,0,Perennial,-
1,1,1/1ecb/10,0,1,party,-
2,2,1/1ecb/10,0,2,girl,-
3,3,1/1ecb/10,0,3,Tara,(HUM16236184328979740
4,4,1/1ecb/10,0,4,Reid,HUM16236184328979740)

In [12]:
with open("ECBplus-prep/output_data/entities_mentions.json") as json_file:
    ecb_entities_mentions = json.load(json_file)

with open("ECBplus-prep/output_data/event_mentions.json") as json_file:
    ecb_events_mentions = json.load(json_file)

### NewsWCL50

In [13]:
newswcl50_mentions = pd.read_csv("NewsWCL50-prep/output_data/all_mentions.csv")
newswcl50_conll = pd.read_csv('NewsWCL50-prep/output_data/conll.csv')

In [14]:
newswcl50_mentions.mention_type.unique()

array(['COUNTRY', 'ACTOR', 'OBJECT', 'GROUP', 'EVENT', 'ACTION'],
      dtype=object)

In [15]:
newswcl50_mentions.shape

(4524, 27)

In [16]:
newswcl50_conll.head()

   Unnamed: 0 topic/subtopic_name/doc  sent_id  token_id  token reference
0           0                 0/0/0_L        0         0   WEST         -
1           1                 0/0/0_L        0         1   PALM         -
2           2                 0/0/0_L        0         2  BEACH         -
3           3                 0/0/0_L        0         3      ,         -
4           4                 0/0/0_L        0         4   Fla.         -

In [17]:
with open("NewsWCL50-prep/output_data/entities_mentions.json") as json_file:
    newswcl50_entities_mentions = json.load(json_file)

with open("NewsWCL50-prep/output_data/event_mentions.json") as json_file:
    newswcl50_events_mentions = json.load(json_file)

In [18]:
len(newswcl50_entities_mentions)

3894

In [19]:
len(newswcl50_events_mentions)

630

#### More entities than events

## MEANTIME

In [20]:
meantime_mentions = pd.read_csv("MEANTIME-prep/output_data/all_mentions.csv").query("language=='english'")
meantime_conll = pd.read_csv('MEANTIME-prep/output_data/conll.csv')
#Still need to filter conll to get only the english mentions

In [21]:
with open("MEANTIME-prep/output_data/entities_mentions.json") as json_file:
    meantime_entities_mentions = json.load(json_file)
    meantime_entities_mentions = [x for x in meantime_entities_mentions if x["language"]=="english"]
with open("MEANTIME-prep/output_data/event_mentions.json") as json_file:
    meantime_events_mentions = json.load(json_file)
    meantime_events_mentions = [x for x in meantime_events_mentions if x["language"]=="english"]

In [22]:
len(meantime_entities_mentions)

3762

In [23]:
len(meantime_events_mentions)

2672

## Summary

In [24]:
len(ecbplus_mentions.coref_chain.unique())

4886

In [25]:
len(ecb_events_mentions)

5000

In [26]:
len(ecb_entities_mentions)

10094

In [27]:
# Print table header
# Define column widths
col_width = 18
format_string= "{:<{}}{:<{}}{:<{}}{:<{}}{:<{}}"
print(format_string.format("Dataset", col_width, "Tokens", col_width, "Coreference Chains", col_width,"Entity mentions", col_width, "Event mentions", col_width))

# Print table rows
print(format_string.format("ECB+", col_width, len(ecbplus_conll), col_width, len(ecbplus_mentions), col_width, len(ecb_entities_mentions), col_width, len(ecb_events_mentions), col_width))
print(format_string.format("newswcl50", col_width, len(newswcl50_conll), col_width, len(newswcl50_mentions), col_width, len(newswcl50_entities_mentions), col_width, len(newswcl50_events_mentions), col_width))
print(format_string.format("meantime", col_width, len(meantime_conll), col_width, len(meantime_mentions), col_width, len(newswcl50_entities_mentions), col_width, len(meantime_events_mentions), col_width))

Dataset           Tokens            Coreference ChainsEntity mentions   Event mentions
ECB+              377367            15094             10094             5000
newswcl50         49591             4524              3894              630
meantime          169227            6434              3894              2672

In [28]:
meantime_mentions.columns

Index(['Unnamed: 0', 'coref_chain', 'mention_ner', 'mention_head_pos',
       'mention_head_lemma', 'mention_head', 'mention_head_id', 'doc_id',
       'doc_id_full', 'is_continuous', 'is_singleton', 'mention_id',
       'mention_type', 'mention_full_type', 'score', 'sent_id',
       'mention_context', 'tokens_number', 'tokens_str', 'tokens_text',
       'topic_id', 'topic', 'subtopic', 'coref_type', 'description',
       'language', 'conll_doc_key'],
      dtype='object')

In [29]:
ecbplus_mentions.head(1)

,Unnamed: 0,coref_chain,mention_ner,mention_head_pos,mention_head_lemma,mention_head,mention_head_id,doc_id,doc,is_continuous,...,tokens_number,tokens_str,tokens_text,topic_id,topic,subtopic_id,subtopic,coref_type,description,conll_doc_key
0,1_10ecb_TIM16236441119149059_3_11_TpBs,TIM16236441119149059,O,ADP,on,on,11,10,1_10ecb,True,...,"[11, 12]",on Tuesday,"['on', 'Tuesday']",1,1,1ecb,T. Reid checks into rehab in 2008,IDENTITY,t1b_friday,1/1ecb/10

In [30]:
import os
def read_files(config, split_name):
    docs_path = os.path.join(config.data_folder, split_name + '.json')
    mentions_path = os.path.join(config.data_folder,
                                    split_name + '_{}.json'.format(config.mention_type))
    with open(docs_path, 'r') as f:
        documents = json.load(f)

    mentions = []
    if config.use_gold_mentions:
        with open(mentions_path, 'r') as f:
            mentions = json.load(f)
    
    return documents

In [31]:
class Config():
    def __init__(self, data_folder,mention_type,use_gold_mentions=True):
        self.data_folder = data_folder
        self.use_gold_mentions= use_gold_mentions
        self.mention_type = mention_type

In [32]:
config = Config(data_folder="ECBplus-prep/output_data/",mention_type="entities",use_gold_mentions=False)

In [33]:
mentions = read_files(config, 'entities_mentions')

In [73]:
mentions[1]['mention_context']

['Tara',
 'Reid',
 'has',
 'entered',
 'a',
 'rehab',
 'program',
 ',',
 'the',
 'American',
 'Pie',
 'star',
 "'s",
 'rep',
 'confirmed',
 'to',
 'People',
 'and',
 'Us',
 'Weekly',
 'on',
 'Friday',
 '.',
 'The',
 'news',
 'comes',
 'as',
 'a',
 'shock',
 'for',
 'everyone',
 'who',
 'just',
 'assumed',
 'the',
 'seldom-seen',
 'actress',
 'had',
 'been',
 'holed',
 'up',
 'there',
 'for',
 'a',
 'while',
 '-',
 'at',
 'least',
 'when',
 'she',
 'was',
 "n't",
 'touring',
 'U.S.',
 'frat',
 'houses',
 'and/or',
 'tequila',
 'conventions',
 '.',
 '``',
 'Tara',
 'Reid',
 'has',
 'checked',
 'herself',
 'into',
 'Promises',
 'Treatment',
 'Center',
 ',',
 "''",
 'Reid',
 "'s",
 'rep',
 'told',
 'Us',
 '.',
 '``',
 'We',
 'appreciate',
 'your',
 'respect',
 'to',
 'her',
 'and',
 'her',
 'family',
 "'s",
 'privacy',
 'at',
 'this',
 'time',
 '.',
 "''",
 'No',
 'specific',
 'reason',
 'or',
 'addiction',
 'was',
 'given',
 'for',
 'her',
 'treatment',
 '.',
 'When',
 'Reid',
 'was',
 "n't",
 'getting',
 'attention',
 'for',
 'her',
 'sometimes',
 'fun/sometimes',
 'scary',
 'breasts',
 ',',
 'the']

In [37]:
import numpy as np
# There does not seem to be lemmas
# lemmas = np.asarray([x['lemmas'] for x in mentions]
topics = set([m['topic'] for m in mentions])

#mention_labels = torch.tensor([m['cluster_id'] for m in mentions])
# There is no coref chain, I will try 'coref_chain'
mentions_list = [m['coref_chain'] for m in mentions]
mention_labels = torch.tensor(mentions_list)

ValueError: too many dimensions 'str'

In [ ]:
# Tensor can't get a list of strings. I will index it temporarily

In [39]:
mentions_list_dict = dict(enumerate(set(mentions_list)))
inv_map = {v: k for k, v in mentions_list_dict.items()}

In [42]:
#mention_labels = torch.tensor([m['cluster_id'] for m in mentions])
# There is no coref chain, I will try 'coref_chain'
mentions_list = [inv_map[m['coref_chain']] for m in mentions]
mention_labels = torch.tensor(mentions_list)

In [44]:
mention_labels.shape

torch.Size([10094])

## Exploring make dict of sentences

In [47]:
import collections

In [45]:
# I will keep it as it is for now given that we don't separate by sentences
def make_dict_of_sentences(documents):
    doc_dict = {}
    for doc, tokens in documents.items():
        dict = collections.defaultdict(list)
        for i, (sentence_id, token_id, text, flag) in enumerate(tokens):
            dict[sentence_id].append([token_id, sentence_id, text, flag])
        doc_dict[doc] = dict

    return doc_dict

In [48]:
#Creates dictionary with list of mention indices as value and topic as key
# This one I would have to edit for those datasets with different definitions of topics/subtopics
mentions_by_topics = collections.defaultdict(list)
for i, m in enumerate(mentions):
    mentions_by_topics[m['topic']].append(i)

In [49]:
from itertools import combinations

In [50]:
combined_list = zip(*list(combinations(range(len(mentions)), 2)))

In [66]:
import math

In [69]:
len(mentions)

10094

In [70]:
math.comb(10094,2)

50939371

In [52]:
temp_list = list(combined_list)

In [64]:
len(mentions)*len(mentions)

101888836

In [62]:
len(temp_list[1])

50939371

In [ ]:
first_list = []
second_list = []
labels_list = []

for topic, mentions in mentions_by_topics.items():
    first, second = zip(*list(combinations(range(len(mentions)), 2)))
    mentions = torch.tensor(mentions)
    first, second = torch.tensor(first), torch.tensor(second)
    first, second = mentions[first], mentions[second]
    labels = (self.mention_labels[first] != 0) & (self.mention_labels[second] != 0) \
                & (self.mention_labels[first] == self.mention_labels[second])

    first_list.extend(first)
    second_list.extend(second)
    labels_list.extend(labels)

In [ ]:
mentions[3]['topic']

'1'